const advisors = [
  {
    profileSlug: 'jim_stone',
    pictureUrl: 'img/team/1.jpg',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jim Stone',
    jobDescription: 'CEO & Founder',
  },
  {
    profileSlug: 'andy_river',
    pictureUrl: 'img/team/2.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Andy River',
    jobDescription: 'CMO',
  },
  {
    profileSlug: 'adele_snow',
    pictureUrl: 'img/team/3.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Adele Snow',
    jobDescription: 'COO',
  },
  {
    profileSlug: 'dylan_woods',
    pictureUrl: 'img/team/4.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Dylan Woods',
    jobDescription: 'Director Finance',
  },

];

const artists = [
  {
    profileSlug: 'jim_stone2',
    pictureUrl: 'img/team/6.jpg',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jim Stone',
    jobDescription: 'Painter',
  },
  {
    profileSlug: 'andy_river1',
    pictureUrl: 'img/team/7.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Andy River',
    jobDescription: 'Scluptor',
  },
  {
    profileSlug: 'adele_snow1',
    pictureUrl: 'img/team/8.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Adele Snow',
    jobDescription: 'Architectect',
  },
  {
    profileSlug: 'dylan_woods1',
    pictureUrl: 'img/team/9.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Dylan Woods',
    jobDescription: 'Rock',
  },
];

const technologists = [
  {
    profileSlug: 'jim_stone3',
    pictureUrl: 'img/team/11.jpg',
    salutation: 'Hi all',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Jim Stone',
    jobDescription: 'CTO',
  },
  {
    profileSlug: 'andy_river3',
    pictureUrl: 'img/team/12.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Andy River',
    jobDescription: 'Front End Developer',
  },
  {
    profileSlug: 'adele_snow3',
    pictureUrl: 'img/team/13.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Adele Snow',
    jobDescription: 'Back End Developer',
  },
  {
    profileSlug: 'dylan_woods3',
    pictureUrl: 'img/team/14.jpg',
    salutation: 'Good Day',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit lacus, a&amp;nbsp;iaculis diam',
    facebookUsername: '',
    twitterUserName: '',
    linkedinUserName: '',
    displayName: 'Dylan Woods',
    jobDescription: 'Dev Operations',
  },
];


export default {
  advisors,
  artists,
  technologists,
};
